name: CI

on:
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-node@v1
      
    - run: yarn

    - name: Install Packages ⏳
      run: yarn install
   
    - name: Build 🧱
      run: yarn build

    - name: Run Tests 🧪
      run: yarn test
